# Generated by Django 3.0.8 on 2020-07-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0008_auto_20200720_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='files/prescriptions'),
        ),
    ]
