# Generated by Django 3.0.8 on 2020-07-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0009_auto_20200720_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='Some-File', upload_to='files/prescriptions'),
        ),
    ]
