# Generated by Django 3.0.8 on 2020-07-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0011_auto_20200720_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(upload_to='files/prescriptions'),
        ),
    ]
