# Generated by Django 3.0.8 on 2020-07-20 13:11

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=120, verbose_name='Problem Name')),
                ('medicine_name', models.CharField(max_length=120, verbose_name='Medicine Name')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('select_time', models.TimeField(default=datetime.datetime(2020, 7, 20, 18, 41, 21, 782438))),
                ('email_id', models.EmailField(default='sivasaikrishna.n18@gmail.com', max_length=254)),
            ],
        ),
    ]
