# Generated by Django 3.0.2 on 2020-03-23 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostics_name', models.CharField(max_length=50)),
                ('report_type', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('report_file', models.FileField(default='Some File', upload_to='files/reports')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload_prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=50)),
                ('disease_name', models.CharField(max_length=15)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('prescription_file', models.FileField(default='Some File', upload_to='files/prescriptions')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
