# Generated by Django 3.0.2 on 2020-03-23 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_prescription',
            name='author',
        ),
        migrations.RemoveField(
            model_name='upload_reports',
            name='author',
        ),
    ]
